name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache dependencies
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Build Docker image
    - name: Build Docker image
      id: build
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t my-image:latest .

    # Push Docker image to registry
    - name: Push Docker image
      run: |
        docker push my-image:latest

    # Example of saving state using environment files instead of save-state
    - name: Save build status to environment file
      run: |
        echo "BUILD_STATUS=success" >> $GITHUB_ENV

    # Example of reading from environment file
    - name: Display build status
      run: |
        echo "The build status is $BUILD_STATUS"

    # Deploy the application (optional step)
    - name: Deploy application
      if: ${{ success() }}
      run: |
        # Your deploy script goes here
        echo "Deploying application..."
